### ISSUE TITLE
error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

### ISSUE THREAD

**Issue by jonnyhtw** [saraqael-m/LifeIn6Lines#1]
Hi there

Thanks for sharing this. I'm excited to give it a go!

I was just wondering if you've seen this error before when running line 2...

```
In [4]: import cv2, numpy as np, scipy.ndimage # import necessary libraries
   ...:

In [5]: img = (cv2.cvtColor(cv2.imread("start.png"),cv2.COLOR_BGR2GRAY)/255+.5).astype("uint8") # get start image
   ...:
---------------------------------------------------------------------------
error                                     Traceback (most recent call last)
<ipython-input-5-d977db7376e3> in <module>
----> 1 img = (cv2.cvtColor(cv2.imread("start.png"),cv2.COLOR_BGR2GRAY)/255+.5).astype("uint8") # get start image

error: OpenCV(4.5.3) /tmp/pip-req-build-dwj9trv5/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

```

Happy to provide more info if need be.

All the best,

Jonny

**Comment by saraqael-m** [comment]
Thank you for your interest in my Github Repo! Actually I think I have got that error when the image "start.png" had the wrong name or wasn't in the same directory as the .py file. The cvtColor function then just receives a "None" object and raises an error. So just look if everything is correct with your start image (name, directory, file ending, ...). Hope you still enjoy this repo!

**Comment by jonnyhtw** [comment]
> Thank you for your interest in my Github Repo! Actually I think I have got that error when the image "start.png" had the wrong name or wasn't in the same directory as the .py file. The cvtColor function then just receives a "None" object and raises an error. So just look if everything is correct with your start image (name, directory, file ending, ...). Hope you still enjoy this repo!

Hi! OK great yes, that's worked now. I won't bore you with the details of that error arising now that I understand what I was doing wrong! 😃 

I'm now getting some great-looking output! Looking forward to playing with this more going forward!

Many thanks & all the best,

Jonny
